"""Añadir columna categoria a EscuelaBasquet

Revision ID: a215ae67c54d
Revises: c326e6186899
Create Date: 2024-08-16 18:32:05.966603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a215ae67c54d'
down_revision = 'c326e6186899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escuela_basquet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=False))

    with op.batch_alter_table('escuela_voley', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escuela_voley', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    with op.batch_alter_table('escuela_basquet', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
