"""empty message

Revision ID: c326e6186899
Revises: 
Create Date: 2024-08-11 19:50:24.038420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c326e6186899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escuela_futbol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escuela_futbol', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
